"""URL routing for the HourSkill app covering pages and JSON APIs."""

from django.urls import path

from . import views


urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('<str:page_name>.html', views.frontend_page, name='frontend_page'),
    path('api/register/', views.api_register, name='api_register'),
    path('api/login/', views.api_login, name='api_login'),
    path('api/manage/courses/', views.api_course_list_create, name='api_course_list_create'),
    path('api/manage/courses/<int:course_id>/', views.api_course_detail, name='api_course_detail'),
    path('api/manage/videos/', views.api_video_list_create, name='api_video_list_create'),
    path('api/manage/videos/<int:video_id>/', views.api_video_detail, name='api_video_detail'),
    path('api/wallet/', views.api_get_wallet, name='api_get_wallet'),
    path('api/profile/', views.api_profile, name='api_profile'),
    path('api/user-profile/', views.api_profile, name='api_user_profile'),
    path('api/me/', views.api_me, name='api_me'),
    path('api/me/check-username/', views.api_check_username, name='api_check_username'),
    path('api/me/update-username/', views.api_me_update_username, name='api_me_update_username'),
    path('api/me/change-password/', views.api_me_change_password, name='api_me_change_password'),
    path('api/me/upload-avatar/', views.api_me_upload_avatar, name='api_me_upload_avatar'),
    path('api/me/remove-avatar/', views.api_me_remove_avatar, name='api_me_remove_avatar'),
    path('api/me/preferences/', views.api_me_preferences, name='api_me_preferences'),
    path('api/user/settings/', views.api_user_settings, name='api_user_settings'),
    path('api/survey/', views.api_survey, name='survey'),
    path('api/select-role/', views.api_select_role, name='select-role'),
    path('api/ping-watch/', views.ping_watch_session, name='ping_watch_session'),
    path('api/upload-video/', views.api_upload_video, name='api_upload_video'),
    path('api/video/<int:video_id>/', views.api_get_video_detail, name='api_get_video_detail'),
    path('api/video/<int:video_id>', views.api_get_video_detail),
    path('api/video/<int:video_id>/comments/', views.api_video_comments, name='api_video_comments'),
    path('api/video/<int:video_id>/comment/', views.api_video_comment, name='api_video_comment'),
    path('api/video/<int:video_id>/unlock/', views.api_unlock_video, name='api_unlock_video'),
    path('api/video/<int:video_id>/unlock', views.api_unlock_video),
    path('api/unlock-video/', views.api_unlock_video_by_body, name='api_unlock_video_by_body'),
    path('api/courses/', views.api_get_courses, name='api_get_courses'),
    path('api/teachers/', views.api_teachers, name='api_teachers'),
    path('api/categories/', views.api_categories, name='api_categories'),
    path('api/follow/', views.api_toggle_follow, name='api_toggle_follow'),
    path('api/follow/<int:creator_id>/', views.api_toggle_follow, name='api_toggle_follow_path'),
    path('api/follow/<int:creator_id>', views.api_toggle_follow),
    path('api/creator/notify-toggle', views.api_creator_notify_toggle, name='api_creator_notify_toggle'),
    path('api/purchase-video/', views.api_purchase_video, name='api_purchase_video'),
    path('api/recharge/', views.api_recharge_tc, name='api_recharge_tc'),
    path('api/purchase-vip/', views.api_purchase_vip, name='api_purchase_vip'),
    path('api/user/vip/renew/', views.api_purchase_vip, name='api_user_vip_renew'),
    path('api/creator/price-eligibility/', views.api_creator_price_eligibility, name='api_creator_price_eligibility'),
    path('api/withdraw-request/', views.api_withdraw_request, name='api_withdraw_request'),
    path('api/post-comment/', views.api_post_comment, name='api_post_comment'),
    path('api/notifications/', views.api_get_notifications, name='api_get_notifications'),
    path('api/notifications/mark-read/', views.mark_notifications_as_read, name='mark_notifications_as_read'),
    path('api/reward-ads/', views.api_reward_ads, name='api_reward_ads'),
    path('api/earn-tc/', views.earn_tc, name='earn_tc'),
    path('api/log-behavior/', views.api_log_behavior, name='api_log_behavior'),
    path('api/channel/', views.api_channel_detail, name='api_channel_detail'),
    path('api/create-course/', views.api_create_course_with_video, name='api_create_course_with_video'),
    path('create-course/', views.create_course, name='create_course'),
    path('api/follow-toggle/', views.api_toggle_follow, name='api_toggle_follow'),
    path("api/video-track/", views.video_tracking),
    path("earn/reward/", views.earn_reward),
]
