# Generated by Django 6.0.2 on 2026-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="duration_seconds",
            field=models.IntegerField(default=0),
        ),
    ]
