# Generated by Django 6.0.2 on 2026-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
