# Generated by Django 6.0.2 on 2026-03-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="wallet_balance",
            field=models.IntegerField(default=5),
        ),
    ]
