# Generated by Django 6.0.2 on 2026-02-24 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0002_category_video_category_commentreview_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="videos",
        ),
        migrations.AddField(
            model_name="video",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="hourskill_app.course",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Tên khóa học"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_videos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
