# Generated by Django 6.0.2 on 2026-03-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0002_alter_video_duration_seconds"),
        ("hourskill_app", "0002_video_video_file"),
    ]

    operations = []
