# Generated by Django 6.0.2 on 2026-03-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0002_alter_video_duration_seconds"),
        ("hourskill_app", "0002_userprofile_wallet_balance"),
    ]

    operations = []
