# Generated by Django 6.0.2 on 2026-02-26 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hourskill_app",
            "0003_remove_course_videos_video_course_alter_course_title_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="file_url",
            new_name="file",
        ),
        migrations.AlterField(
            model_name="video",
            name="duration_seconds",
            field=models.IntegerField(default=0, help_text="Thời lượng video (giây)"),
        ),
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
