# Generated by Django 6.0.2 on 2026-03-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0002_alter_category_id_alter_commentreview_id_and_more"),
        ("hourskill_app", "0003_merge_20260306_0158"),
    ]

    operations = []
