# Generated by Django 6.0.2 on 2026-02-26 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="SUCCESS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("EARN_ADS", "Earn TC from ads"),
                    ("SPEND_VIEW", "Spend TC to view"),
                    ("EARN_CREATOR", "Creator earns TC from viewers"),
                    ("DEPOSIT_VND", "Deposit VND"),
                    ("WITHDRAW_VND", "Withdraw VND"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_creator",
            field=models.BooleanField(
                default=False, help_text="Creator accounts can upload content"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_vip",
            field=models.BooleanField(
                default=False, help_text="VIP users have paid VND benefits"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="trust_score",
            field=models.IntegerField(
                default=100, help_text="Lower scores indicate suspicious activity"
            ),
        ),
        migrations.AlterField(
            model_name="userbehavior",
            name="video_timestamp_seconds",
            field=models.IntegerField(
                default=0,
                help_text="Timestamp within the video when the event happened",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="duration_seconds",
            field=models.IntegerField(help_text="Length of the video in seconds"),
        ),
        migrations.AlterField(
            model_name="watchsession",
            name="is_unlocked",
            field=models.BooleanField(
                default=False, help_text="True once TC payment is completed"
            ),
        ),
    ]
