# Generated by Django 6.0.2 on 2026-03-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourskill_app', '0004_merge_20260306_2133'),
        ('hourskill_app', '0004_merge_20260306_2134'),
    ]

    operations = [
    ]
