# Generated by Django 6.0.2 on 2026-03-28 04:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0008_video_is_standalone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("30.00"), max_digits=12
            ),
        ),
    ]
