# Generated by Django 6.0.2 on 2026-03-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0015_dual_currency_financial_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("rating", "Rating"),
                    ("purchase", "Purchase"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("RECHARGE", "Recharge TC via VND"),
                    ("VIP_PURCHASE", "VIP package purchase"),
                    ("CONTENT_SALE", "Paid content sale"),
                    ("EARN_ADS", "Earn TC from ads"),
                    ("SPEND_VIEW", "Spend TC to view"),
                    ("EARN_CREATOR", "Creator earns TC from viewers"),
                    ("DEPOSIT_VND", "Deposit VND"),
                    ("BUY_VIP", "Buy VIP package"),
                    ("WITHDRAW_VND", "Withdraw VND"),
                    ("VIEW_POINT", "View point accrual for creator"),
                ],
                max_length=20,
            ),
        ),
    ]
