# Generated by Django 6.0.2 on 2026-03-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0007_userprofile_dark_mode"),
        ("hourskill_app", "0016_alter_notification_notification_type_and_more"),
    ]

    operations = []
