# Generated by Django 6.0.2 on 2026-03-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hourskill_app", "0018_video_prerequisite_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category_text",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="hourskill_app.category",
            ),
        ),
    ]
